//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using ScriptWordEnum = ScriptWords.ScriptWordEnum;
using AssemblyCSharp.Level;

public class ScriptHandler
{
    public ScriptHandler() {
    }

    public static void process(Script script) {
        if(script != null){
			// perform method
            // invoke method with arguments
            
            string[] param = script.target;
            string method = script.script;

            ScriptWordEnum eVal = ScriptWords.getSWEValues()[method];
            switch(eVal){

                case ScriptWordEnum.movePlayer:
                    ScriptWords.movePlayer( param[0] ); 
                    break;

                case ScriptWordEnum.giveToPlayer:
                    ScriptWords.giveToPlayer( param[0] ); 
                    break;

                case ScriptWordEnum.takeFromPlayer:
                    ScriptWords.takeFromPlayer( param[0] ); 
                    break;

                default:
                    // no method found!
                    break;
            }

        }
    }
}

