//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

[System.Serializable]
public sealed class PlayerResourceTypes   {
	
	private readonly String name;
	private readonly int value;


	public static readonly PlayerResourceTypes WOOD = new PlayerResourceTypes (1, "wood");
	public static readonly PlayerResourceTypes BRICK = new PlayerResourceTypes (2, "brick");
	public static readonly PlayerResourceTypes STEEL = new PlayerResourceTypes (3, "steel");
	
	public static readonly PlayerResourceTypes MONEY = new PlayerResourceTypes (4, "money");
	public static readonly PlayerResourceTypes CONCRETE = new PlayerResourceTypes (5, "concrete");
	
	private PlayerResourceTypes(int value, String name){
		this.name = name;
		this.value = value;
	}
	
	public override String ToString(){
		return name;
	}
	public int Value(){
		return value;
	}
}

