//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

[System.Serializable]
public class BuildingPackage  {
	public PlayerResourceTypes prType;

}

//public class StringValue : System.Attribute
//{
//	private string _value;
//	
//	public StringValue(string value)
//	{
//		_value = value;
//	}
//	
//	public string Value
//	{
//		get { return _value; }
//	}
//	
//}
//
//public enum AuthenticationMethod
//{
//	[StringValue("FORMS")]
//	FORMS = 1,
//	[StringValue("WINDOWS")]
//	WINDOWSAUTHENTICATION = 2,
//	[StringValue("SSO")]
//	SINGLESIGNON = 3
//}
//
//public static class StringEnum
//{
//	public static string GetStringValue(Enum value)
//	{
//		string output = null;
//		Type type = value.GetType();
//		
//		//Check first in our cached results...
//		
//		//Look for our 'StringValueAttribute' 
//		
//		//in the field's custom attributes
//		
//		FieldInfo fi = type.GetField(value.ToString());
//		StringValue[] attrs =
//			fi.GetCustomAttributes(typeof(StringValue),
//			                       false) as StringValue[];
//		if (attrs.Length > 0)
//		{
//			output = attrs[0].Value;
//		}
//		
//		return output;
//	}
//}

