//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using System.Xml;
using System.Xml.Serialization;

namespace AssemblyCSharp.Level
{
    [XmlRoot("DialogContent")]
    public class DialogContent{

        [XmlAttribute ("id")]
        public long id;

        [XmlElement ("content")]
        public string content;

        [XmlAttribute ("name")]
        public string name;

        [XmlIgnore]
        public bool foldContent = true;
        [XmlIgnore]
        public bool isUnFolded = true;
        [XmlIgnore]
        public bool isChecked = false;

        public DialogContent(){ }

        public DialogContent(long id, string content, string name) {
            this.id = id;
            this.content = content;
            this.name = name;
        }
    }
}

