//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

using System.Xml;
using System.Xml.Serialization;

namespace AssemblyCSharp.Level
{
    public class DialogNode{

        [XmlAttribute ("id")]
        public long id;

        [XmlAttribute ("contentId")]
        public long contentId;

        [XmlElement ("Nodes")]
        public List<DialogNode> children = new List<DialogNode>();

        [XmlIgnore]
        public bool isChecked = false;

        [XmlIgnore]
        public bool isUnFolded = false;


        public DialogNode(){
            children = new List<DialogNode>();
        }

        public DialogNode(long id, long contentId) {
            this.id = id;
            this.contentId = contentId;
            children = new List<DialogNode>();
        }
    }

    [XmlRoot("DialogTree")]
    public class DialogTree{
        
        
        [XmlAttribute ("lastId")]
        public long lastId;

        [XmlElement ("Content")]
        public List<DialogContent> content;

        [XmlElement ("Nodes")]
        public List<DialogNode> nodes;

        public DialogTree(){
            nodes = new List<DialogNode>();
        }

        public DialogTree(List<DialogNode> dNodes, List<DialogContent> dContent) {
            nodes = new List<DialogNode>();
            nodes.AddRange(dNodes);

            content = new List<DialogContent>();
            content.AddRange(dContent);
        }
    }
}

