//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

using System.Xml;
using System.Xml.Serialization;

namespace AssemblyCSharp.Level {

    public class ItemTemplate {
        [XmlAttribute ("id")]
        public long id;

        // [XmlElement]

        [XmlAttribute ("name")]
        public string name;

        [XmlAttribute ("script")]
        public string script;

        [XmlAttribute ("sTarget")]
        public string sTarget;
        

        [XmlIgnore]
        public bool isUnFolded = true;
        [XmlIgnore]
        public bool isChecked = false;

        public ItemTemplate() { }
        
        public ItemTemplate(long id, string name) {
            this.id = id;
            this.name = name;
        }
    }

    [XmlRoot("ItemList")]
    public class ItemList{

        [XmlAttribute ("lastId")]
        public long lastId;
        
        [XmlElement ("Item")]
        public List<ItemTemplate> items;

        public ItemList(){ }

        public ItemList(List<ItemTemplate> itemsList){
            this.items = itemsList;
        }
    }
}

